USE JAVACARD; 
GO

CREATE TABLE transacoes_bancaria (
    ID_TRANSACAO INT PRIMARY KEY IDENTITY,
    ID_CONTA INT,
    DATA_TRANSACAO DATE,
    VALOR_TRANSACAO DECIMAL(10, 2),
    ID_TIPO INT,
    FOREIGN KEY (ID_CONTA) REFERENCES conta_bancaria (ID_CONTA),
    FOREIGN KEY (ID_TIPO) REFERENCES tipo_bancaria (ID_TIPO)
);
GO

SELECT * FROM transacoes_bancaria;
GO